### ISSUE TITLE
JSON list responses can't be unmarshalled due to JSON tags on embedded structs

### ISSUE THREAD

**Issue by pauln** [nsip/sifxml2go#11]
We're currently working with the NSW Department of Education to migrate our integration from their XML-based 3PI platform to their new SAIS platform, which instead uses PESC JSON (based on the [SIF-AU v3.5.0 OpenAPI spec](http://specification.sifassociation.org/Implementation/AU/3.5.0/ServiceDocs/Full.html)).  As we use the data structures provided by this library, we were hoping that the change from XML to JSON would be relatively painless - but we've found that responses containing lists of entities are unable to be unmarshalled due to the JSON tags on the embedded structs.

For example, the StudentPersonal struct currently looks like this:
```go
type StudentPersonal struct {
    studentpersonal `xml:"StudentPersonal" json:"StudentPersonal"`
}
```

This means that in order to unmarshall an array, each element must be wrapped in an extra layer containing only a "StudentPersonal" key, i.e.
```json
[
  {
    "StudentPersonal": {
      "RefId": "refid-1-goes-here",
      ...
    }
  },
  {
    "StudentPersonal": {
      "RefId": "refid-2-goes-here",
      ...
    }
  }
]
```

This "wrapper" isn't present on the individual elements in the [responses defined in the OpenAPI spec](http://specification.sifassociation.org/Implementation/AU/3.5.0/ServiceDocs/Full.html#tag/StudentPersonal/operation/getStudentPersonals) (and thus returned by SAIS) - the entire array sits under a key which specifies the entity type, i.e.
```json
{
  "StudentPersonals": {
    "StudentPersonal": [
      {
        "RefId": "refid-1-goes-here",
        ...
      },
      {
        "RefId": "refid-2-goes-here",
        ...
      }
    ]
  }
}
```

As long as the "extra wrapping" on the individual elements isn't needed to support any other existing SIF-AU services (i.e. states other than NSW), this could perhaps be addressed by either removing the JSON tag from the embedded structs, i.e.
```go
type StudentPersonal struct {
    studentpersonal `xml:"StudentPersonal"`
}
```

or replacing the tag with an `xml.Name` attribute (which the XML (un)marshaller will still map to the tag name, but the JSON (un)marshaller will ignore):
```go
import "encoding/xml" 
type StudentPersonal struct {
    XMLName xml.Name `xml:"StudentPersonal"`
    studentpersonal
}
```

Do you think either of those would be viable from your side - or do you have any other suggestions for how we can handle these responses (either within this library, or at our end)?

**Comment by opoudjis** [comment]
@pauln Thank you for your PR; it takes me a couple of weeks to get through my backlog, which is why I haven't responded until now.

You're right that the JSON presentation in this gem is incompatible with the PESC JSON approach to lists, and that therefore I will need to either build a custom marshaller, or adopt something like what you have suggested. I like the XMLName approach; I'll review the output tomorrow.

This code has not been used in anger yet: we use it to generate our own testbed's SIF objects, but we've been using only XML to date. I am not aware of any external use. So yes, accepting this change will not break anything; I just need to test it out for myself!

Really grateful, and pleasantly surprised, that you found this code, btw.

**Comment by pauln** [comment]
@opoudjis We were grateful for the existence of this code - it saved us from having to build up the data structures ourselves!

I also like the XMLName approach, but I don't speak Perl and so didn't have the time to figure out how to inject the import (if needed) and XMLName attribute in the right places - hence my removal of JSON tag, which was straightforward and sufficient to let us proceed with our development (using a `replace` directive in `go.mod` to point at my fork for now).  I popped a PR in just in case you wanted to go down that route - please feel free to ignore/reject the PR and implement a nicer/cleaner solution (such as XMLName)!

**Comment by opoudjis** [comment]
Tinkered, and I've come up with a solution, though it's not as neat. The issue is that I need to be able to marshal and unmarshal both single objects, and object lists; so I can't just remove the name StudentPersonal from JSON. What I will end up doing is:

````
type StudentPersonals struct {
        studentpersonallist `json:"StudentPersonals"`
}

type studentpersonallist struct {
        StudentPersonal []studentpersonal `json:"StudentPersonal"`
}

type StudentPersonal struct {
        studentpersonal `xml:"StudentPersonal" json:"StudentPersonal"`
}

type studentpersonal struct {
...
}
````

and for that to work, I need to change the list processing in the SDK, so that it adds the anonymous struct studentpersonal to lists, not the eponymous StudentPersonal, which will retain its struct name.

Hopefully will get this done tonight.

**Comment by opoudjis** [comment]
Btw, I'm very happy to report that I have now forgotten my Perl (I switched to Ruby a little before I originally wrote that code), so I'm now struggling with the build scripts :)

**Comment by opoudjis** [comment]
It won't be done tonight, but good chance of Monday.

**Comment by opoudjis** [comment]
To clarify: the structs are done, but I'm still working on the accessor methods.

**Comment by pauln** [comment]
Ah - we're only dealing with lists of records at the moment, so I hadn't thought to check how it affected individual records, sorry.

We currently use our own "wrapper" structs for list responses, which look something like this:
```go
type StudentPersonalsResponse struct {
	StudentPersonalsList `xml:"StudentPersonals" json:"StudentPersonals"`
}

type StudentPersonalsList struct {
	StudentPersonals []*sifxml.StudentPersonal `xml:"StudentPersonal" json:"StudentPersonal"`
}
```

Coupled with either of the changes in my original post, these work with both the XML and JSON responses.  We're happy to either continue using them (tweaked if necessary) - or, if your changes enable us to, drop them in favour of structs provided directly by the `sifxml` package.

**Comment by opoudjis** [comment]
Oh, crap. I only saw this now. As it turns out, I've already implemented those wrappers, and I'm trying to realise coherent access to them. I'm dogfooding them in my object generator here. I have pretty much cracked it, and am updating the code. 

So object list objects, like StudentPersonals, do need different treatment from objects proper, like StudentPersonal. I've also taken the opportunity to do some tidy up. So, using StudentPersonal as an exemplar:

* I have created a .ToSlice() method, converting *StudentPersonals to []*StudentPersonal; that's how you iterate the contents of StudentPersonals
* I still have .Last and .Index on StudentPersonals, though I don't think they'll work well
* I've made .Append variadic, so you can do x.Append(slice...)
* I've got rid of the silly checking of StudentPersonalPointer: the initialiser is now NewStudentPersonal and NewStudentPersonals, and it will return a pointer to the object struct invoked, instead of you having to do &StudentPersonal{}

The populate/*.go code is an exemplar of how this works, and I recommend perusal of it. I'm sorry I've gone ahead without checking in on what you've been doing, but we're getting there. 

Please do review my current code and make suggestions! Should be up in a couple of hours.

**Comment by opoudjis** [comment]
Updated. Have at it!

**Comment by opoudjis** [comment]
````
a := sifxml.NewStudentPersonal()
ret := sifxml.NewStudentPersonals()
ret.Append(a)
ret2 := sifxml.NewStudentPersonals()
ret.Append(ret2.ToSlice()...)
````

**Comment by pauln** [comment]
Thanks, that's great!  A quick bit of initial testing suggests that it's working nicely for both XML and JSON responses - and it lets us ditch our "response" wrapper structs, which is a nice bonus 👍🏼 

Would you mind tagging a new version?  I've used the specific commit for now, which generates a pseudo-version in `go.mod`, but it'd be nice to be able to point it at a proper version tag 😉

**Comment by opoudjis** [comment]
https://github.com/nsip/sifxml2go/releases/tag/v0.1.0
